---
title: "rectangular grid into irregular spatial polygon"
---
Code to make an **R** function [rectBySpacing()]{style="font-family: monospace; background-color: #e8e8e8;"} to populate an irregular polygon with rectangular grid points at defined x (and optionally y) spacings. At present this is only written for a simple boundary - one area, with no holes!

```{r rectByspacing function, results='hold'}
rectBySpacing <-
  function(boundary,
           xspacing,
           yspacing = xspacing,
           xoffset = 0,
           yoffset = xoffset,
           epsg = NULL
  ) {
    require(sf) # we're using simple features
    # if projection not defined, set to EPSG:4326 (WGS84 LongLat)
    if (is.null(epsg)) {
      ep <-
        st_crs(4326)
    } else {
      ep <- st_crs(epsg)
    }

    # make boundary coordinates into SpatialPolygons object
    # irregpoly <- st_as_sf(boundary[, c(3,4)], coords = c("Longitude","Latitude"),
    #                       crs=ep)
    irregpoly <- st_polygon(list(as.matrix(boundary)))
    irregpoly <- st_sf(st_sfc(irregpoly, crs = ep))
    irregPolys <- st_multipolygon(list(irregpoly))
    irregSpatialPolys = SpatialPolygons(list(irregPolys),
                                        proj4string = p4)

    # define limits of initial (maximal) grid
    extremes <- c(min(floor(boundary[, 1])),
                  min(floor(boundary[, 2])),
                  max(ceiling(boundary[, 1])),
                  max(ceiling(boundary[, 2])))
    # calculate areas
    area <- st_area(irregpoly)
    grid_big <- st_sf(st_cast(st_make_grid(irregpoly,
                                           cellsize=c(xspacing,yspacing)),
                              "MULTIPOINT"), crs = ep)
    grid_big <- st_sf(st_make_grid(irregpoly, cellsize = c(xspacing, yspacing),
                             what = "corners"), crs = ep)
    maxPoly <- st_polygon(list(cbind(st_bbox(grid_big)[c(1,1,3,3,1)],
                                  st_bbox(grid_big)[c(2,4,4,2,2)])))
    maxarea <- st_area(st_sf(st_sfc(maxPoly), crs = ep))

    plot(grid_big)
    axis(1);axis(2);box()
    plot(points_in,col="red",pch=19,add=T)
    lines(st_coordinates(irregpoly),col="#0000FF80",lwd=4)

    # use points_in() function from sf package to mask initial grid
    points_in <- st_intersection(grid_big, irregpoly)
    # convert masked coordinates back into data frame

    # make output object
    output <-
      list(
        points_in = inside,
        x_spacing = xspacing,
        y_spacing = yspacing,
        x_offset = xoffset,
        y_offset = yoffset,
        npoints = NROW(inside),
        max_points = NROW(grid_big),
        shape_area = area,
        max_area = maxarea,
        extremes = c(min(floor(boundary[, 1])),
                     min(floor(boundary[, 2])),
                     max(ceiling(boundary[, 1])),
                     max(ceiling(boundary[, 2]))),
        epsg = ep
      )
    return(output)
```
    

# testing the rectBySpacing function
SVbound <- read.csv("sv_boundary.csv")
RFbound <- read.csv("RFboundary.csv")
RFdesign <-
  rectBySpacing(RFbound,
                xspacing = 320,
                yspacing = 320,
                xoffset = 5,
                yoffset = 50,
                proj4 = "+proj=utm +zone=50 +south")
str(RFdesign)
# -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
# check with a plot
par(
  mfrow = c(1, 1),
  mar = c(3, 3, 1, 1),
  mgp = c(1.6, 0.3, 0),
  tcl = 0.25,
  font.lab = 2,
  lend = 2,
  ljoin = 1,
  cex.axis = 0.8
)
with(RFbound, plot(Easting, Northing, asp = 1, type = "l"))
rect(RFdesign$extremes[1], RFdesign$extremes[2],
     RFdesign$extremes[3], RFdesign$extremes[4],
     border = "chocolate",
     lty = 2)
points(RFdesign$points_in,
       col = "purple",
       pch = 3,
       cex = 0.8)

legend(
  "topleft",
  inset = 0.04,
  y.intersp = 1.2,
  bty = "o",
  box.col = 8,
  title = expression(bold("Rectangular Grid Sampling Design")),
  legend = c(
    paste0("Spacing = ", RFdesign$x_spacing,"\u00D7",RFdesign$y_spacing), 
    paste0("  offset = ", RFdesign$x_offset,"\u00D7",RFdesign$y_offset),
    paste("Irregular polygon", signif(RFdesign$shape_area, 5), "m\u00B2"),
    paste("Max. extent", signif(RFdesign$max_area, 6), "m\u00B2")
  ),
  cex = 0.9, pch = c(3, NA, NA, NA),
  col = c("purple", NA, 1, "chocolate"),
  lty = c(NA, NA, 1, 2)
)
mtext(paste(
  "Polygon contains",
  RFdesign$npoints,
  "points from maximal grid of",
  RFdesign$max_points, "points"), 
  3, -1, col = "grey50", font = 3)
mtext("UWA Ridgefield Farm, Pingelly", 
  side = 3, line = 0.1, 
  col = "#27348B", font = 2, 
  cex = 0.9, family = "serif")
